<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d51b18b6-aa46-4af0-a2f0-e17fd28939bd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.7" />
    <PackageReference Include="QuestPDF" Version="2025.7.3" />
  </ItemGroup>

</Project>
